name: flutter_support_chat
description: Flutter package to implement a firestore chat between customer and
  product support
version: 2.0.0
homepage: https://github.com/cedtegApps/flutter_support_chat
repository: https://github.com/cedtegApps/flutter_support_chat
issue_tracker: https://github.com/cedtegApps/flutter_support_chat/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  adaptive_dialog: ">=2.0.0 <3.0.0"
  cloud_firestore: ">=4.0.0 <5.0.0"
  device_info_plus: ">=9.0.0 <10.0.0"
  firebase_core: ">=1.2.0 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - example/web/index.html
