name: flutter_support_chat
description: Flutter plugin for implemening a support chat
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
